apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-hgwemjdl
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-hgwemjdl:f2b002f883a934304eedc032c19ba30a2d439d85@sha256:7e6ee615c1b377374fe9c89499112067c2bca9d9b455b0ef08383e08a9b399f8
          name: container-image
